server:
  port: 8089
spring:
  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
#      jdbc-url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&&autoReconnect=true&failOverReadOnly=false


mybatis-plus:
    #  global-config:
    #    db-config:
    #      logic-delete-field: is_delete  #全局逻辑删除字段值 3.3.0开始支持
    #      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
    #      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath*:mapper/**/*.xml